name: Build ZMK Firmware

on:
  push:
    branches:
      - charybdis
  pull_request:
    branches:
      - charybdis
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Zephyr dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip ninja-build cmake gcc-arm-none-eabi gperf
          pip3 install --user west

      - name: Fetch ZMK firmware
        run: |
          git clone --depth 1 https://github.com/zmkfirmware/zmk.git zmk_firmware
          cd zmk_firmware
          west init -l app
          west update
          west
